### ISSUE TITLE
Queue Actions

### ISSUE THREAD

**Issue by AngelZatch** [TeamBerry/cranberry#10]
## Queue Actions
- [x] Queue Actions revealed on tap
- [x] Link buttons to their API actions
- [x] Apply ACL
- [x] Berries context
- [x] Use Options Patch API to quickly toggle Shuffle, Loop, Berries & Duration Restriction options
- [ ] Display Feedback Message as SnackBar

## Search Actions
- [x] Search Actions auto-displayed
- [x] Link buttons to their API actions
- [x] Apply ACL
- [x] Berries context
- [ ] Display Feedback Message as SnackBar
